version: '3.3'
networks:
  mqtt:
    external: true
services:
  emqx:
    container_name: emqx
    networks:
      - mqtt
    ports:
      - '1883:1883'
      - '8083:8083'
      - '8084:8084'
      - '8883:8883'
    image: 'emqx:latest'
    environment:
      # - EMQX_LISTENER__SSL__DEFAULT__SSL_OPTIONS__KEYFILE:"/certs/${DOMAIN}/privkey.key"
      # - EMQX_LISTENER__SSL__DEFAULT__SSL_OPTIONS__CERTFILE:"/certs/${DOMAIN}/fullchain.crt"
      # - EMQX_LISTENER__SSL__DEFAULT__SSL_OPTIONS__CACERTFILE:"/certs/private/letsencrypt.key"
      # - EMQX_LISTENER__WSS__DEFAULT__WSS_OPTIONS__KEYFILE:"/certs/${DOMAIN}/privkey.key"
      # - EMQX_LISTENER__WSS__DEFAULT__WSS_OPTIONS__CERTFILE:"/certs/${DOMAIN}/fullchain.crt"
      # - EMQX_LISTENER__WSS__DEFAULT__WSS_OPTIONS__CACERTFILE:"/certs/private/letsencrypt.key"
      - EMQX_LOG__CONSOLE_HANDLER__LEVEL=error
    volumes:
      - /home/ubuntu/app/emqx/data:/opt/emqx/data
      - /home/ubuntu/emqx-mqtt/traefik/certs/certs:/certs
      - ./emqx.conf:/opt/emqx/etc/emqx.conf
      - /home/ubuntu/app/emqx/log:/opt/emqx/log
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.emqx.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.emqx.entrypoints=websecure"
      - "traefik.http.routers.emqx.tls.certresolver=letsencrypt"
      - "traefik.http.services.emqx.loadbalancer.server.port=18083"

# emqx  | EMQX_NODE__NAME [node.name]: emqx@emqx.mqtt.maulik.tech
# emqx  | Listener ssl:default on 0.0.0.0:8883 started.
# emqx  | Listener tcp:default on 0.0.0.0:1883 started.
# emqx  | Listener ws:default on 0.0.0.0:8083 started.
# emqx  | Listener wss:default on 0.0.0.0:8084 started.
# emqx  | Listener http:dashboard on :18083 started.
