---
version: "3"
services:
  traefik:
    image: traefik:latest
    container_name: traefik
    network_mode: "host"
    restart: unless-stopped
    command:
      - --log.level=DEBUG
      - --accessLog.filePath=/logs/access.log # ? Log path - optional - related to volume /logs defined above
      - --accessLog.bufferingSize=100
      # Tell Traefik to discover containers using the Docker API
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      # Enable the Trafik dashboard
      - --api.dashboard=true
      # Set up LetsEncrypt
      - --certificatesresolvers.letsencrypt.acme.dnschallenge=true
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.letsencrypt.acme.email=${EMAIL_ADDRESS}
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      # Set up an insecure listener that redirects all traffic to TLS
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.websecure.address=:443
      # Set up the TLS configuration for our websecure listener
      - --entrypoints.websecure.http.tls=true
      - --entrypoints.websecure.http.tls.certResolver=letsencrypt
      - --entrypoints.websecure.http.tls.domains[0].main=${DOMAIN}
      - --entrypoints.websecure.http.tls.domains[0].sans=*${DOMAIN}
    environment:
      - CLOUDFLARE_EMAIL=${EMAIL_ADDRESS}
      - CLOUDFLARE_DNS_API_TOKEN=${CLOUDFLARE_DNS_API_TOKEN}
      - PUID=1000
      - PGID=1000
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/letsencrypt
      - ./logs:/logs
    labels:
      - "traefik.enable=true"
      - 'traefik.http.routers.traefik.rule=Host(`dash.mqtt.maulik.tech`)'
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"
      - "traefik.http.routers.traefik.service=api@internal"
      - 'traefik.http.routers.traefik.middlewares=strip'
      - 'traefik.http.middlewares.strip.stripprefix.prefixes=/traefik'
  traefik-certs-dumper:
    image: ldez/traefik-certs-dumper:v2.8.1
    environment:
      - PUID=1000
      - PGID=1000
    entrypoint: sh -c '
      apk add jq
      ; while ! [ -e /data/acme.json ]
      || ! [ `jq ".[] | .Certificates | length" /data/acme.json` != 0 ]; do
      sleep 1
      ; done
      && traefik-certs-dumper file --domain-subdir --crt-name=fullchain --key-name=privkey --version v2 --watch
      --source /data/acme.json --dest /data/certs --post-hook "chown -R 1000:1000 /data/certs"'
    volumes:
      - ./certs:/data
