version: '3.4'
networks:
  mqtt:
    external: true
services:
  manager:
    networks:
      - mqtt 
    image: emqx/ekuiper-manager:latest
    container_name: ekuiper-manager
    ports:
      - "9082:9082"
    restart: unless-stopped
    environment:
      # setting default eKuiper service, works since 1.8.0
      DEFAULT_EKUIPER_ENDPOINT: "http://ekuiper:9081"
  ekuiper:
    image: lfedge/ekuiper:latest
    networks:
      - mqtt 
    ports:
      - "9081:9081"
      - "127.0.0.1:20498:20498"
    container_name: ekuiper
    hostname: ekuiper
    restart: unless-stopped
    user: root
    volumes:
      - /home/ubuntu/app/kuiper/data:/kuiper/data
    environment:
      MQTT_SOURCE__DEFAULT__SERVER: "tcp://emqx:1883"
      KUIPER__BASIC__CONSOLELOG: "true"
      KUIPER__BASIC__IGNORECASE: "false"
